###### user account register
POST  http://localhost:5400/mochileros/v1/account/customer HTTP/1.1
Content-Type: application/json

{
    "email": "lukas.adnres@gmail.com",
    "password": "Lamisma123*"
}

#### 
POST  http://localhost:5400/mochileros/v1/account/user HTTP/1.1
Content-Type: application/json

{
    "email": "lucas.andres@gmail.com"
}

#### 
POST  http://localhost:5400/mochileros/v1/account/user/d840e3eb-d219-4734-9d9d-b589e5f4de0b/kyc HTTP/1.1
Content-Type: application/json

{
    "FirstName": "Lucas Jose",
    "LastName": "Marsell"
}

#### 
GET   http://localhost:5400/mochileros/v1/account/user/d840e3eb-d219-4734-9d9d-b589e5f4de0b HTTP/1.1
Content-Type: application/json

{}


#### 
PUT   http://localhost:5400/mochileros/v1/account/user/d840e3eb-d219-4734-9d9d-b589e5f4de0b/status HTTP/1.1
Content-Type: application/json

{}


######
GET    http://localhost:5400/mochileros/v1/migration/countries HTTP/1.1
Content-Type: application/json

{}


######
GET    http://localhost:5400/mochileros/v1/props/country HTTP/1.1
Content-Type: application/json

{}